# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework: INFO
    edu:
      eci:
        arsw:
          blueprints: DEBUG
